- name: Create Job Block
  loop: "{{sjobs}}"
  block:
- name: Copy XML File
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: item.job_name
    password: admin123
    url: http://172.31.8.150:8080
    user: admin